name: gendiff-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gendiff project check
        uses: hexlet/project-action@release
        with:
          hexlet-id: ${{ secrets.HEXLET_ID }}
      - name: Run linter and pytest
        run: |
      - name: Code Coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 4f804d1381ef468f39911b55b9aeec541d22ecd2438c25ac68d92b996fcc5a32
        with:
          coverageCommand: make test-coverage
          debug: true
