name: gendiff-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gendiff project check
        uses: hexlet/project-action@release
        with:
          hexlet-id: ${{ secrets.HEXLET_ID }}
      - name: Run linter and pytest
        run: |
      - name: Test & publish code coverage
          uses: paambaati/codeclimate-action@v3.2.0
          env:
            CC_TEST_REPORTER_ID: <code_climate_reporter_id>
          with:
            coverageCommand: npm run coverage
            debug: true