- name: Pytest Coverage Comment
  # You may pin to the exact commit or the version.
  # uses: MishaKav/pytest-coverage-comment@c29468a3db43bfb9e0b5f85b43bfd06b39b582ba
  uses: MishaKav/pytest-coverage-comment@v1.1.37
  with:
    # GitHub API Access Token
    github-token: # default is ${{ github.token }}
    # The location of the txt output of pytest-coverage
    pytest-coverage-path: # optional, default is ./pytest-coverage.txt
    # The location of coverage-xml from pytest-coverage
    pytest-xml-coverage-path: # optional, default is 
    # Prefix for path when link to files in comment
    coverage-path-prefix: # optional, default is 
    # Title for the coverage report. Useful for monorepo projects
    title: # optional, default is Coverage Report
    # Title for the badge icon
    badge-title: # optional, default is Coverage
    # Hide badge with percentage
    hide-badge: # optional, default is false
    # Hide coverage report
    hide-report: # optional, default is false
    # Hide the whole comment (use when you need only `output`)
    hide-comment: # optional, default is false
    # Show in report only changed files for this commit, and not all files
    report-only-changed-files: # optional, default is false
    # The location of the junitxml path
    junitxml-path: # optional, default is 
    # Title for summary for junitxml
    junitxml-title: # optional, default is 
    # When false, will update the same comment, otherwise will publish new comment on each run
    create-new-comment: # optional, default is false
    # This branch name is usefull when generate "coverageHtml", it points direct links to files on this branch (instead of commit). Usually "main" or "master"
    default-branch: # optional, default is main
    # You can pass array of titles and files to generate single comment with table of results.  Single line should look like `Title, ./path/to/pytest-coverage.txt, ./path/to/pytest.xml` example: 
  My Title 1, ./data/pytest-coverage_3.txt, ./data/pytest_1.xml

    multiple-files: # optional, default is 
    # When true, it will remove the link from badge to readme
    remove-link-from-badge: # optional, default is false
